### ISSUE TITLE
[NFR] menu aim integration

### ISSUE THREAD

**Issue by crnjakovic** [vadikom/smartmenus#21]
Hi, I think it would be great if smartmenus would make use of https://github.com/kamens/jQuery-menu-aim for making sub-menus more forgiving instead of delaying show/hide? :)

**Comment by vadikom** [comment]
Hi, thanks for your suggestion! I will investigate the possibility to add a similar feature. It's quite a bit more complicated adding this to the SmartMenus plugin since the sub menus might appear in any direction in certain scenarios (so using the jQuery-menu-aim plugin verbatim is not an option) but it should be possible nonetheless.

If you want my honest opinion though, I always had the feeling there is something wrong with that Amazon dropdown. In general, it does the trick of showing the dropdowns immediately but it's prone to misbehaving and activating the incorrect sub menu in some cases. Maybe it's possible to tweak the detection for the cursor movement a bit better but still I doubt this can work flawlessly especially with multilevel sub menus.
