### ISSUE TITLE
Problems with Bootstrap Navbar

### ISSUE THREAD

**Issue by eccentricworx** [vadikom/smartmenus#23]
Hi,
i just had a look to your demos included in the download-package and noticed that in you bootstrap example dropdown parent links are not working when navbar switches to vertical version on smaller screen-sizes.
It simply closes instead of forwarding to the link... while the normal-screen version is working fine...

**Comment by vadikom** [comment]
Yep, the Bootstrap addon currently adheres to the default Bootstrap navbar behavior which is to use the parent items in collapsible mode just as toggles for their sub menus. If you would like to restore the default SmartMenus behavior, you can do so by following the instructions in the following forum post:

http://www.smartmenus.org/forums/topic/smartmenus-and-drupal-bootstrap-theme/#post-1734

This will most probably be changed in the next release due to high user demand and then it will be possible to activate the links in parent items and at the same time the sub indicators will act as toggles for their sub menus.

**Comment by eccentricworx** [comment]
Great, it works very fine now. you saved my day!!
Many thanks!
