### ISSUE TITLE
Short timing gap on Chrome

### ISSUE THREAD

**Issue by aberndt** [vadikom/smartmenus#25]
Using this wonderful plugin in Chrome causes some timing gaps. When the page is loaded, the menu is shortly shown without the dropdown arrows. After some milliseconds (probably around 100) the menu is shown as expected.

**Comment by vadikom** [comment]
Hi, this happens ondomready when the script initializes the menu because by default the sub menu indicator arrows are generated dynamically. If you would like to avoid this effect, you can include the arrows "manually" in your HTML source:
```html
<li><a href="#"><span class="sub-arrow">+</span>Menu item text</a>...
```
and use the <code>subIndicators: false</code> script option.

**Comment by aberndt** [comment]
Perfect, thanks. Works like a charm :)
