### ISSUE TITLE
Click on menu items not working when "A" element "display" CSS attribute is different from "block"

### ISSUE THREAD

**Issue by Erika31** [vadikom/smartmenus#37]
It is not true to assume that a visible block has always the CSS "display" attribute equals to "block" (it can be "inline-block", "flex" or "inline-flex", or even something else...)

Btw, click is working when line 416 is replaced by :

```javascript
return this.$firstLink.css('display') != 'none';
```

**Comment by vadikom** [comment]
Yep, of course, you are right on theory. But it is actually assumed that users won't need to change the default `display: block` set for the menu links in "sm-core-css.css" since the links are wrapped in LI elements and normally you could achieve all kinds of layouts by tweaking the LI's `display` instead. Could you please explain why do you need to change the links' `display`? Maybe also share a demo URL if possible?

The line of code you mention is inside the isCSSOn() method and its purpose is to detect when CSS support might be disabled in the user agent so your modification would break it. You could use:
```javascript
return this.$firstLink.css('display') != 'inline';
```
if you need to set the `display` to something different from `inline` (which is the default value as per the spec).
