### ISSUE TITLE
Option to change the default method of returning focus to the parent item.

### ISSUE THREAD

**Issue by klonos** [vadikom/smartmenus#50]
Hello @vadikom, you might be happy to know that we have chosen SmartMenus for implementing a drop-down menu solution in [Backdrop CMS](backdropcms.org).

One of the things that stroke me strange was the fact that you need to use the Esc key in order to move back out to the parent menu item. I realize that this is to accommodate for using the up/down keys in order to cycle through the menu items (jump to first child from the last one), but it would be usefull if there was an option to change that so that the up key returned you to the top-level menu and the down key just stopped the navigation to the last menu item.

Is that possible already?

**Comment by klonos** [comment]
...the issue where we are implementing the drop-down feature is [this](https://github.com/backdrop/backdrop-issues/issues/2107).

The specific part where we discuss this issue there is: https://github.com/backdrop/backdrop-issues/issues/2107#issuecomment-246292568

**Comment by vadikom** [comment]
Hi @klonos, of course, I am happy to hear that! :) Hope the integration goes smooth!

Like you've found out already:

> . When the last item is reached, the next key tap moves the active menu back to the first one (and the reverse). In our case, this was not obvious because we need #2160

the up/down keys cycle through the current menu's items (actually the same goes for the left/right keys for a horizontal main menu). This is indeed a feature (desktop menus on Windows and to some extend macOS function similarly) and currently there is no way to disable it but I will consider providing an option in the next release of the keyboard add-on.

I ran quickly through your issue so here are some comments to annoyances you've mentioned:

> Reaching the last child of a series of submenus and hitting the right key should do nothing (that's what I personally expect?), but it jumps to the next top-level menu item instead.

This is again a feature and mimics the way desktop menus function in macOS/Windows.

> When a series of submenus reaches the end of the screen, smartmenus lives up to its name and starts unfolding the menus to the left ( 👍 this prevents the menus from being rendered outside the viewport), but navigating to them works by the right arrow key. WTF?! (I'd expect this to switch to left instead).

Yeah, at first swapping left/right in that case seems logical but there is a major problem with that. Imagine we swap left/right in the following case:

![screen shot 2016-09-14 at 5 14 21 pm](https://cloud.githubusercontent.com/assets/288808/18515667/c0903af0-7a9e-11e6-831b-1ff8f7b883eb.png)

Now what should happen on "left" - move to the parent item or to the sub menu? :) I believe this is one of the reasons desktop sub menus function like SmartMenus (again :) ) - "left" always goes to the parent and "right" to the sub menu (except, of course, in RTL mode where it's reversed).

> I would expect that hovering over the menu with the mouse makes the item active and I can then continue navigation via the keyboard. This does not happen though.

This is a nice idea! I will consider implementing it in a sensible way (it we simply focus the hovered item, I believe it would cause issues in some cases but, as I am thinking, it might possibly be implemented in a more unobtrusive way.)

> Menus with to many top-level menu items fold to a second line of menus (might be confusing).

Yeah, the items are floated and this is the way floats work in CSS - the good thing is that at least the items remain usable. There are, of course, some possible approaches to avoid this "issue" like this custom (still not official) addon I created a while ago which adds a dynamic "More" last main menu item and hides proper main menu items if needed to prevent wrapping:

http://www.smartmenus.org/forums/topic/desktop-menu-when-more-item-clicked/

I guess there might be other sensible approaches too but I don't personally think this issue is a show stopper and it only happens in certain cases and it could also be avoided just via CSS.
