### ISSUE TITLE
Submenu links on iPad (Chrome emulation)

### ISSUE THREAD

**Issue by kartemov** [vadikom/smartmenus#51]
Hi there,

I was looking at SmartMenus Bootstrap Addon (Navbar) demo and tried it using Google Chrome's Emulator. When I selected an iPad in landscape mode I noticed an issue that you can't expand the submenu on tap (highlighted) -- it just closes the whole menu.
![bug](https://cloud.githubusercontent.com/assets/1385171/18605255/b7106f3c-7c5a-11e6-8eca-f0c81a880884.PNG)

Thanks!

**Comment by sajansharmanz** [comment]
Must be some issue in the emulator. I have just been using it this morning to develop a website and it has been working on all my device properly (android mobile, ipad and laptop pc)

**Comment by vadikom** [comment]
Sorry, for the delay! Just tested this myself. Indeed there seems to be something wrong when testing with Chrome's emulation. I will try to figure out what happens when I have a bit more time but this is definitely not happening on a real device or even the iOS Simulator bundled with Xcode on macOS so no need to worry.
