### ISSUE TITLE
JQuery 3.0 support?

### ISSUE THREAD

**Issue by LaFut** [vadikom/smartmenus#53]
hello.
If I use Jquery 3.0 with connected Jqmigrate I have 3 warnings in console about deprecated methods.

> JQMIGRATE: jQuery.fn.bind() is deprecated
> init    @   jquery.smartmenus.js:151
> 
> JQMIGRATE: jQuery.fn.delegate() is deprecated
> init    @   jquery.smartmenus.js:156

**Comment by vadikom** [comment]
Yep, this is because both methods are deprecated as of jQuery 3.0. Though they seem to be bundled and working for now.

Anyway, I am investigating what would be the best approach to go forward - there are two possibilities:

1) Drop support for jQuery < 1.7 (currently we support 1.4.4+) and rely just on the on/off methods;
2) Add some bloat to the code to rely on on/off in jQuery 1.7+ and continue using (un)bind/(un)delegate in jQuery < 1.7.

I will try to figure out what's the better option soon - maybe it's 2) for now which can easily be turned into 1) in the future.

**Comment by vadikom** [comment]
These should be fixed now in 1.1.0. I've migrated to on/off instead of (un)bind/(un)delegate - and the script now supports jQuery 1.7.0+.
