### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by lewebsimple** [vadikom/smartmenus#57]
Do you plan on porting smartmenus to Bootstrap 4?
Could you provide some idea of where to star / what this would implyt?
Thanks !

**Comment by vadikom** [comment]
Yes, there will surely be an addon at some point but since Bootstrap 4 is still in alpha I’d prefer to wait a bit more for it. So for now you would need to use a generic SmartMenus navbar with some theme like this one, for example:

http://www.smartmenus.org/about/themes/#themes-5

You could also customize it further if you like.

As for idea - the JS of the addon will be similar but there are some differences compared to Bootstrap 3 that will need to be handled. For example, in Bootstrap 4 they use DIV/A elements for the dropdowns in their default samples which will need to be replaced by an UL/LI/A structure, they no longer use caret elements but add the dropdown indicators via CSS, etc. It's not a big deal to solve all these but I would really prefer to wait at least until Bootstrap 4 is in beta.

**Comment by vadikom** [comment]
Bootstrap 4 is now in "beta" so an official Bootstrap 4 addon has landed with the 1.1.0 release. We've added some demos too:

http://vadikom.github.io/smartmenus/src/demo/

Cheers!
