### ISSUE TITLE
z-index reset upon scrolling start (when menu is longer than page height).

### ISSUE THREAD

**Issue by klonos** [vadikom/smartmenus#59]
I've noticed this issue while trying to troubleshoot https://github.com/backdrop/backdrop-issues/issues/2161...

There is a `z-index` of 10001 applied to the `<ul>` of expanded menus that go beyond the height of the page. It is applied once you hover over the parent menu and the menu is expanded. The same `z-index` is also applied to the `scroll-up` and `scroll-down` `<span>`s. Soon as there is a scroll event on the mouse though, the `z-index` is removed from the `<ul>` (still retained on the scroll `<span>`s):

![smartmenus-z-index_gone_after_scroll](https://cloud.githubusercontent.com/assets/2423362/21370343/58588222-c75f-11e6-9ecc-8abe63f78db5.gif)

**Comment by vadikom** [comment]
Nope, the `z-index` of the `<ul>` is only reset after it is hidden not onscroll. In your case, the style value just seems to be truncated in the dev tools view (since it's too long) but the `z-index` declaration is still active, you can be sure of that.

I will now check the linked issue you mentioned and see if I could be of any help...

**Comment by klonos** [comment]
Yep, double-checked and you are right that the `z-index` is there. Don't know what is going on then. Hmm?
