### ISSUE TITLE
Missing option to change the default toggle functionality of the hamburger menu (mobile sizes menu)

### ISSUE THREAD

**Issue by AlexRebula** [vadikom/smartmenus#63]
First I would like to say that this plugin menu is something extraordinary. You guys did a really great job, especially because you included the accessibility support (screen readers, keyboard navigation etc.). Kudos guys, kudos! :)

That being said I have a an issue with the lack of one specific functionality that could have been included in the plugin's options.

We implemented this menu on a website, but once all was done, they came back to us saying that they would rather avoid having the hamburger menu double-click functionality to open the page and would rather have the possibility to expand / toggle the menu item by clicking / tapping the plus (+) button on the right side of the navigation item. So that if the item is a link to a website, the user would directly click on that item and that would not expand to show the children items but would rather take them to the linked website. Only clicking the the plus (+) on the right side of the item would toggle the item.

Meaning that we would not have not only one link in the item but rather a link to redirect and a toggle button next to that link. Something like it's done here (resize the window to mobile size and expand the menu): https://lighthouse.opencities.com

Is it possible that I have missed this functionality? Or is it possible to add it? I was actually thinking to do a fork and do an extension myself if you would consider this being useful.

Please, let me know, I look forward hearing from you about this.

Thank you a lot, 

Alex

**Comment by vadikom** [comment]
Hey Alex, happy to hear you like the script!

There are a number of possible ways parent items, sub menu indicators and sub menus could behave in collapsible mode (e.g. use the whole item just as a toggle button, work like accordion by resetting other branches, use the item and indicator separately so the link loads on first tap, etc.) and I've seen users preferring different approaches. So in general it would be nice to allow changing the current default behavior via an option and I have, of course, considered this in the past. But at least for now, I have not done it since it would bloat the code quite a bit if I add support for all possible cases.

So for now everything is possible with a bit of additional code that uses the API. I have posted a number of solutions in the forums and adding some demos and documenting all the cases is in my TODO list (I'm just not sure when I will get to these tasks).

Anyway, here is the code that will do the trick in your case:
https://www.smartmenus.org/forums/topic/href-not-working-on-parent-as-expected/#post-3025

**Comment by AlexRebula** [comment]
Hi!

Thank you for your response and the script, I appreciate it. I will try it. I did not have lots of time to work on it extending the options to include my preference yet, but will definitely try.

Cheers!
