### ISSUE TITLE
Active lin problem

### ISSUE THREAD

**Issue by gvoxcms** [vadikom/smartmenus#72]
I testet the newest version of smartmenu(codepen) together with pages - not just linking to Yor .com . When i klick on a link then  the title gets a smaller fontsize and the letters touch the upper border . 
I added a class to the span of  the chosen link (with jquery) and cannot hinder - either with align:center and similar styles - that the letters of the selected submenus touch the left border(lineheight:35px and fontsize:20px brought it back. but...).
Most important 👎 
When i klick in an element of the upper(!) menulevel then the site appears but the dropdown is away and no more choosable. I have to klick on another li-element of the toplevel and then the dropdown of the frozen element comes back.

**Comment by gvoxcms** [comment]
The problem is caused by a <span> around the active link - this should be corrected -perhaps You can give a code here. A  Jquery $...remove() for the span soles the problem.

**Comment by gvoxcms** [comment]
http://net.square7.ch/cmxh169curl/  with deep  active links colored green for demonstration
A Jquery $...remove() for the span solves the problem.

**Comment by vadikom** [comment]
The problem is server-side. For example, when the "Welcome to CMSimple XH" is not selected, the server output the following HTML:

```html
<li class="docs"><a href="/cmxh169curl/Welcome_to_CMSimple_XH">Welcome to CMSimple XH</a>
```

and when it's selected it outputs a SPAN element instead of the link:

```html
<li class="sdocs"><span>Welcome to CMSimple XH</span>
```

The best approach is to check the server-side code that generates your menu structure and make sure it always outputs the link.

If you are unable to edit that code, you could use a hacky JS solution - something like this called before the SmartMenus init call:
```javascript
$('.nav li > span').each(function() {
  var $this = $(this);
  $this.replaceWith('<a href="#">' + $this.text() + '</a>');
});
```
This will replace the SPAN with a dummy link and your parent items should display their sub menus without any problems.
