### ISSUE TITLE
Add option to prevent the parents' anchors from following href

### ISSUE THREAD

**Issue by turakvlad** [vadikom/smartmenus#78]
At first I would like to thank you for this great plugin!

I'd like to suggest one enhancement. I have the Bootstrap menu with 3 levels deep and `{ noMouseOver: true }` option and it works great, but I faced with one problem: when I click on the parent's node, the menu with children nodes will open and it's okey, but if I click once again on the same parent's node, I will be redirected to the `href` that was specified for this `<a>`.

For example, in the mobile view when I click on the `+` / `-` button the current menu toggles (shows and hides). I'd like to have the same behavior when I click on the entire parent's node.

Please, look at this screenshot:
![screenshot from 2017-08-19 18-09-34](https://user-images.githubusercontent.com/7996184/29488371-96ccff2a-8509-11e7-94a6-d8f30cc9a663.png)

When I click on the `-` the menu toggles, but when I click on the entire node's element the browser will redirect me to the `href`.

So, I'd like only the children nodes (the deepest level) could be able to follow the `href`. Not the parent ones.

Thanks in advance!

**Comment by vadikom** [comment]
Thanks, for the suggestion! I will think about possible option(s) to control the behavior in collapsible mode since this is requested quite often.

For now you have 2 options to achieve it:

1) Since you are using the Bootstrap add-on, you could add the `data-sm-skip-collapsible-behavior="true"` attribute to your `.navbar-nav` UL element:
https://www.smartmenus.org/docs/#data-sm-skip-collapsible-behavior

2) If you'd like to keep the +/- button visually, don't use the `data-sm-skip-collapsible-behavior="true"` attribute but instead add the following JS on your page:
https://www.smartmenus.org/forums/topic/hide-submenu-of-clicked-menu-item-only/#post-2714
(just change the selector inside the sample code from `$('#main-menu')` to something like `$('.navbar-nav')`)

**Comment by vadikom** [comment]
It's much simpler now in 1.1.0 (with Bootstrap addon 0.4.0) to modify the behavior with the new option `collapsibleBehavior `:

https://www.smartmenus.org/docs/#collapsibleBehavior

So in your case you could also use something like:

```html
<ul class="nav navbar-nav" data-sm-options="{ collapsibleBehavior: 'toggle' }">...
```
